logging:
  level:
    root: info

# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
          jdbc-url: jdbc:h2:file:C:/devpets/projects
    driver-class-name: org.h2.Driver
    username: sa
    password:

# JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true